import type { Characteristic } from '@/types';

/** 特性 */
export const CHARACTERISTICS: Characteristic[] = [
  {
    id: 1,
    group: 1,
    name: '秀麗',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: -1 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.5, trickish: 0.0 },
    flavorText: '美人薄命。',
  },
  {
    id: 2,
    group: 1,
    name: '醜悪',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 1 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: -0.5, trickish: 0.0 },
    flavorText: '能力的にはこっちの方が得。',
  },
  {
    id: 3,
    group: 2,
    name: '高貴の出',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: -0.5, brave: 0.5, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
    flavorText: '高貴だから良い人という事は言えない。',
  },
  {
    id: 4,
    group: 2,
    name: '下賎の出',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: -0.5, cheerful: 0.0, trickish: 0.5 },
    flavorText: '先天的な物でする苦労は大抵理不尽だ…',
  },
  {
    id: 5,
    group: 3,
    name: '都会育ち',
    physical: { agility: 0, dexterity: 0, intelligence: 1, mind: 0, strength: 0, vitality: -1 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.5, trickish: 0.5 },
    flavorText: '得る物も失う物も多い場所。',
  },
  {
    id: 6,
    group: 3,
    name: '田舎育ち',
    physical: { agility: -1, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 1 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: -0.5 },
    flavorText: 'そこには安らぎがあるかもしれない。',
  },
  {
    id: 7,
    group: 4,
    name: '裕福',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: -1, strength: 0, vitality: 0 },
    mental: { aggressive: -0.5, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: -0.5 },
    flavorText: '登場するなら金よこせ！',
  },
  {
    id: 8,
    group: 4,
    name: '貧乏',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 1, strength: 0, vitality: 0 },
    mental: { aggressive: 0.5, brave: -0.5, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
    flavorText: '同情するなら金をくれ！',
  },
  {
    id: 9,
    group: 5,
    name: '厚き信仰',
    physical: { agility: 0, dexterity: 0, intelligence: -1, mind: 1, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.5, cautious: 0.0, cheerful: 0.0, trickish: -0.5 },
    flavorText: '存在を信じるのか、信頼を寄せるのか…',
  },
  {
    id: 10,
    group: 5,
    name: '不心得者',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.5, cheerful: 0.0, trickish: 0.5 },
    flavorText: '供養より施行より稼業。',
  },
  {
    id: 11,
    group: 6,
    name: '誠実',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.5, cautious: 0.0, cheerful: 0.0, trickish: -0.5 },
    flavorText: 'いつかは報われると思いたい物だ…',
  },
  {
    id: 12,
    group: 6,
    name: '不実',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: -0.5, cautious: 0.0, cheerful: 0.0, trickish: 0.5 },
    flavorText: '過度の嘘は身を滅ぼす。',
  },
  {
    id: 13,
    group: 7,
    name: '冷静沈着',
    physical: { agility: -1, dexterity: 0, intelligence: 1, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.5, cheerful: 0.0, trickish: 0.5 },
    flavorText: '急いては事をし損じる。',
  },
  {
    id: 14,
    group: 7,
    name: '猪突猛進',
    physical: { agility: 1, dexterity: 0, intelligence: 0, mind: -1, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: -0.5, cheerful: 0.0, trickish: 0.0 },
    flavorText: '先手必勝。',
  },
  {
    id: 15,
    group: 8,
    name: '貪欲',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: -1, strength: 0, vitality: 1 },
    mental: { aggressive: 0.5, brave: -0.5, cautious: -0.5, cheerful: 0.0, trickish: 0.0 },
    flavorText: '求めるが故に失う物も有る…。',
  },
  {
    id: 16,
    group: 8,
    name: '無欲',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: -0.5, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
    flavorText: '食欲ぐらいは残しておこうよ。',
  },
  {
    id: 17,
    group: 9,
    name: '献身的',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 1, strength: 0, vitality: -1 },
    mental: { aggressive: -0.5, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
    flavorText: '自己犠牲は時として暴走する事も有る。',
  },
  {
    id: 18,
    group: 9,
    name: '利己的',
    physical: { agility: 1, dexterity: -1, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.5, brave: 0.0, cautious: 0.0, cheerful: -0.5, trickish: 0.5 },
    flavorText: '…その形質が表面に出るとは限らない。',
  },
  {
    id: 19,
    group: 10,
    name: '秩序派',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.5, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: -0.5 },
    flavorText: '秩序の頂点に立つ者は混沌。',
  },
  {
    id: 20,
    group: 10,
    name: '混沌派',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: -1, strength: 1, vitality: 0 },
    mental: { aggressive: 0.5, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: 0.5 },
    flavorText: '自由は他人に押し付ける物では無いかと…',
  },
  {
    id: 21,
    group: 11,
    name: '進取派',
    physical: { agility: 1, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: -1 },
    mental: { aggressive: 0.0, brave: 0.5, cautious: -0.5, cheerful: 0.0, trickish: 0.0 },
    flavorText: '勇み足には注意せよ。',
  },
  {
    id: 22,
    group: 11,
    name: '保守派',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 1, strength: -1, vitality: 0 },
    mental: { aggressive: -0.5, brave: 0.0, cautious: 0.5, cheerful: 0.0, trickish: 0.0 },
    flavorText: '運命に逆らうのは、ただ一度。',
  },
  {
    id: 23,
    group: 12,
    name: '神経質',
    physical: { agility: 1, dexterity: 0, intelligence: 0, mind: 0, strength: -1, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.5, cheerful: -0.5, trickish: 0.0 },
    flavorText: '度が過ぎるとパラノイアになるかもね。',
  },
  {
    id: 24,
    group: 12,
    name: '鈍感',
    physical: { agility: 0, dexterity: 0, intelligence: -1, mind: 0, strength: 0, vitality: 1 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
    flavorText: '場の空気位は読めた方が便利。',
  },
  {
    id: 25,
    group: 13,
    name: '好奇心旺盛',
    physical: { agility: 0, dexterity: 1, intelligence: 0, mind: 0, strength: 0, vitality: -1 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
    flavorText: '飽き性にはならない様に。',
  },
  {
    id: 26,
    group: 13,
    name: '無頓着',
    physical: { agility: -1, dexterity: 0, intelligence: 0, mind: 1, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: -0.5, trickish: 0.0 },
    flavorText: '興味無いね。',
  },
  {
    id: 27,
    group: 14,
    name: '過激',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 1, vitality: -1 },
    mental: { aggressive: 0.5, brave: 0.0, cautious: -0.5, cheerful: 0.0, trickish: 0.0 },
    flavorText: '過ぎたるは及ばざるが如し。',
  },
  {
    id: 28,
    group: 14,
    name: '穏健',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: -0.5, brave: 0.0, cautious: 0.5, cheerful: 0.0, trickish: 0.0 },
    flavorText: '事なかれ主義？',
  },
  {
    id: 29,
    group: 15,
    name: '楽観的',
    physical: { agility: -1, dexterity: 1, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.5, cautious: -0.5, cheerful: 0.0, trickish: 0.0 },
    flavorText: '勇気と無謀は別物。',
  },
  {
    id: 30,
    group: 15,
    name: '悲観的',
    physical: { agility: 0, dexterity: 0, intelligence: 1, mind: -1, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: -0.5, cautious: 0.5, cheerful: 0.0, trickish: 0.0 },
    flavorText: '期待しなければ傷つく事も無い…か。',
  },
  {
    id: 31,
    group: 16,
    name: '勤勉',
    physical: { agility: 0, dexterity: -1, intelligence: 0, mind: 0, strength: 0, vitality: 1 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
    flavorText: '日々勉強よ。',
  },
  {
    id: 32,
    group: 16,
    name: '遊び人',
    physical: { agility: 0, dexterity: 1, intelligence: -1, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.5, trickish: 0.5 },
    flavorText: '賢者に転職…は出来ません。',
  },
  {
    id: 33,
    group: 17,
    name: '陽気',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.5, trickish: 0.0 },
    flavorText: '陽気＝いい人と言う訳では無いらしい。',
  },
  {
    id: 34,
    group: 17,
    name: '内気',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: -0.5, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
    flavorText: '内気＝陰気とは少し違う気も。',
  },
  {
    id: 35,
    group: 18,
    name: '派手',
    physical: { agility: 1, dexterity: 0, intelligence: -1, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: -0.5, cheerful: 0.5, trickish: 0.0 },
    flavorText: '派手なら目立つってモンでも無い気が…',
  },
  {
    id: 36,
    group: 18,
    name: '地味',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: -1, vitality: 1 },
    mental: { aggressive: 0.0, brave: -0.5, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
    flavorText: '地味なら渋いかと言うと、そうでも無い。',
  },
  {
    id: 37,
    group: 19,
    name: '高慢',
    physical: { agility: 0, dexterity: -1, intelligence: 0, mind: 1, strength: 0, vitality: 0 },
    mental: { aggressive: 0.5, brave: 0.0, cautious: 0.0, cheerful: -0.5, trickish: 0.0 },
    flavorText: 'それ行け、やれ行け、どんと行け！',
  },
  {
    id: 38,
    group: 19,
    name: '謙虚',
    physical: { agility: 0, dexterity: -1, intelligence: 1, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.5, cheerful: 0.0, trickish: 0.0 },
    flavorText: '毒にも薬にもならないかも。',
  },
  {
    id: 39,
    group: 20,
    name: '上品',
    physical: { agility: 0, dexterity: 0, intelligence: 1, mind: 0, strength: -1, vitality: 0 },
    mental: { aggressive: -0.5, brave: 0.0, cautious: 0.0, cheerful: 0.5, trickish: 0.0 },
    flavorText: '上品な口調で下品な事は言わないように。',
  },
  {
    id: 40,
    group: 20,
    name: '粗野',
    physical: { agility: 0, dexterity: 0, intelligence: -1, mind: 0, strength: 1, vitality: 0 },
    mental: { aggressive: 0.5, brave: 0.0, cautious: 0.0, cheerful: -0.5, trickish: 0.0 },
    flavorText: 'ガラの悪い台詞になる事が多い気がする…',
  },
  {
    id: 41,
    group: 21,
    name: '武骨',
    physical: { agility: 0, dexterity: -1, intelligence: 0, mind: 0, strength: 1, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.5, cautious: 0.0, cheerful: -0.5, trickish: 0.0 },
    flavorText: '小細工なんて大嫌い～♪',
  },
  {
    id: 42,
    group: 21,
    name: '繊細',
    physical: { agility: 0, dexterity: 1, intelligence: 0, mind: 0, strength: -1, vitality: 0 },
    mental: { aggressive: 0.0, brave: -0.5, cautious: 0.5, cheerful: 0.0, trickish: 0.0 },
    flavorText: '繊細を自称すると変な目で見られるぞ。',
  },
  {
    id: 43,
    group: 22,
    name: '硬派',
    physical: { agility: -1, dexterity: 0, intelligence: 0, mind: 0, strength: 1, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.5, cautious: 0.0, cheerful: 0.0, trickish: -0.5 },
    flavorText: '堅苦しい奴だと思われること請け合い？',
  },
  {
    id: 44,
    group: 22,
    name: '軟派',
    physical: { agility: 0, dexterity: 1, intelligence: 0, mind: -1, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: -0.5, cautious: 0.0, cheerful: 0.5, trickish: 0.0 },
    flavorText: '〆る時位は〆て下さいね。',
  },
  {
    id: 45,
    group: 23,
    name: 'お人好し',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.5, trickish: -0.5 },
    flavorText: 'いいひと。',
  },
  {
    id: 46,
    group: 23,
    name: 'ひねくれ者',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: -0.5, trickish: 0.0 },
    flavorText: '又の名を天の邪鬼？',
  },
  {
    id: 47,
    group: 24,
    name: '名誉こそ命',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.5, cautious: -0.5, cheerful: 0.0, trickish: -0.5 },
    flavorText: '名声の方が現実的やね。',
  },
  {
    id: 48,
    group: 24,
    name: '愛に生きる',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: -0.5, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
    flavorText: '哀なら知っているけどな…',
  },
];
