import type { Characteristic } from '@/types';

/** 特性 */
export const CHARACTERISTICS: Characteristic[] = [
  {
    id: 1,
    group: 1,
    name: '秀麗',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: -1 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.5, trickish: 0.0 },
  },
  {
    id: 2,
    group: 1,
    name: '醜悪',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 1 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: -0.5, trickish: 0.0 },
  },
  {
    id: 3,
    group: 2,
    name: '高貴の出',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: -0.5, brave: 0.5, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 4,
    group: 2,
    name: '下賎の出',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: -0.5, cheerful: 0.0, trickish: 0.5 },
  },
  {
    id: 5,
    group: 3,
    name: '都会育ち',
    physical: { agility: 0, dexterity: 0, intelligence: 1, mind: 0, strength: 0, vitality: -1 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.5, trickish: 0.5 },
  },
  {
    id: 6,
    group: 3,
    name: '田舎育ち',
    physical: { agility: -1, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 1 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: -0.5 },
  },
  {
    id: 7,
    group: 4,
    name: '裕福',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: -1, strength: 0, vitality: 0 },
    mental: { aggressive: -0.5, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: -0.5 },
  },
  {
    id: 8,
    group: 4,
    name: '貧乏',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 1, strength: 0, vitality: 0 },
    mental: { aggressive: 0.5, brave: -0.5, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 9,
    group: 5,
    name: '厚き信仰',
    physical: { agility: 0, dexterity: 0, intelligence: -1, mind: 1, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.5, cautious: 0.0, cheerful: 0.0, trickish: -0.5 },
  },
  {
    id: 10,
    group: 5,
    name: '不心得者',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.5, cheerful: 0.0, trickish: 0.5 },
  },
  {
    id: 11,
    group: 6,
    name: '誠実',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.5, cautious: 0.0, cheerful: 0.0, trickish: -0.5 },
  },
  {
    id: 12,
    group: 6,
    name: '不実',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: -0.5, cautious: 0.0, cheerful: 0.0, trickish: 0.5 },
  },
  {
    id: 13,
    group: 7,
    name: '冷静沈着',
    physical: { agility: -1, dexterity: 0, intelligence: 1, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.5, cheerful: 0.0, trickish: 0.5 },
  },
  {
    id: 14,
    group: 7,
    name: '猪突猛進',
    physical: { agility: 1, dexterity: 0, intelligence: 0, mind: -1, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: -0.5, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 15,
    group: 8,
    name: '貪欲',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: -1, strength: 0, vitality: 1 },
    mental: { aggressive: 0.5, brave: -0.5, cautious: -0.5, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 16,
    group: 8,
    name: '無欲',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: -0.5, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 17,
    group: 9,
    name: '献身的',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 1, strength: 0, vitality: -1 },
    mental: { aggressive: -0.5, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 18,
    group: 9,
    name: '利己的',
    physical: { agility: 1, dexterity: -1, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.5, brave: 0.0, cautious: 0.0, cheerful: -0.5, trickish: 0.5 },
  },
  {
    id: 19,
    group: 10,
    name: '秩序派',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.5, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: -0.5 },
  },
  {
    id: 20,
    group: 10,
    name: '混沌派',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: -1, strength: 1, vitality: 0 },
    mental: { aggressive: 0.5, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: 0.5 },
  },
  {
    id: 21,
    group: 11,
    name: '進取派',
    physical: { agility: 1, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: -1 },
    mental: { aggressive: 0.0, brave: 0.5, cautious: -0.5, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 22,
    group: 11,
    name: '保守派',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 1, strength: -1, vitality: 0 },
    mental: { aggressive: -0.5, brave: 0.0, cautious: 0.5, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 23,
    group: 12,
    name: '神経質',
    physical: { agility: 1, dexterity: 0, intelligence: 0, mind: 0, strength: -1, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.5, cheerful: -0.5, trickish: 0.0 },
  },
  {
    id: 24,
    group: 12,
    name: '鈍感',
    physical: { agility: 0, dexterity: 0, intelligence: -1, mind: 0, strength: 0, vitality: 1 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 25,
    group: 13,
    name: '好奇心旺盛',
    physical: { agility: 0, dexterity: 1, intelligence: 0, mind: 0, strength: 0, vitality: -1 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 26,
    group: 13,
    name: '無頓着',
    physical: { agility: -1, dexterity: 0, intelligence: 0, mind: 1, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: -0.5, trickish: 0.0 },
  },
  {
    id: 27,
    group: 14,
    name: '過激',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 1, vitality: -1 },
    mental: { aggressive: 0.5, brave: 0.0, cautious: -0.5, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 28,
    group: 14,
    name: '穏健',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: -0.5, brave: 0.0, cautious: 0.5, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 29,
    group: 15,
    name: '楽観的',
    physical: { agility: -1, dexterity: 1, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.5, cautious: -0.5, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 30,
    group: 15,
    name: '悲観的',
    physical: { agility: 0, dexterity: 0, intelligence: 1, mind: -1, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: -0.5, cautious: 0.5, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 31,
    group: 16,
    name: '勤勉',
    physical: { agility: 0, dexterity: -1, intelligence: 0, mind: 0, strength: 0, vitality: 1 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 32,
    group: 16,
    name: '遊び人',
    physical: { agility: 0, dexterity: 1, intelligence: -1, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.5, trickish: 0.5 },
  },
  {
    id: 33,
    group: 17,
    name: '陽気',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.5, trickish: 0.0 },
  },
  {
    id: 34,
    group: 17,
    name: '内気',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: -0.5, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 35,
    group: 18,
    name: '派手',
    physical: { agility: 1, dexterity: 0, intelligence: -1, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: -0.5, cheerful: 0.5, trickish: 0.0 },
  },
  {
    id: 36,
    group: 18,
    name: '地味',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: -1, vitality: 1 },
    mental: { aggressive: 0.0, brave: -0.5, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 37,
    group: 19,
    name: '高慢',
    physical: { agility: 0, dexterity: -1, intelligence: 0, mind: 1, strength: 0, vitality: 0 },
    mental: { aggressive: 0.5, brave: 0.0, cautious: 0.0, cheerful: -0.5, trickish: 0.0 },
  },
  {
    id: 38,
    group: 19,
    name: '謙虚',
    physical: { agility: 0, dexterity: -1, intelligence: 1, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.5, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 39,
    group: 20,
    name: '上品',
    physical: { agility: 0, dexterity: 0, intelligence: 1, mind: 0, strength: -1, vitality: 0 },
    mental: { aggressive: -0.5, brave: 0.0, cautious: 0.0, cheerful: 0.5, trickish: 0.0 },
  },
  {
    id: 40,
    group: 20,
    name: '粗野',
    physical: { agility: 0, dexterity: 0, intelligence: -1, mind: 0, strength: 1, vitality: 0 },
    mental: { aggressive: 0.5, brave: 0.0, cautious: 0.0, cheerful: -0.5, trickish: 0.0 },
  },
  {
    id: 41,
    group: 21,
    name: '武骨',
    physical: { agility: 0, dexterity: -1, intelligence: 0, mind: 0, strength: 1, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.5, cautious: 0.0, cheerful: -0.5, trickish: 0.0 },
  },
  {
    id: 42,
    group: 21,
    name: '繊細',
    physical: { agility: 0, dexterity: 1, intelligence: 0, mind: 0, strength: -1, vitality: 0 },
    mental: { aggressive: 0.0, brave: -0.5, cautious: 0.5, cheerful: 0.0, trickish: 0.0 },
  },
  {
    id: 43,
    group: 22,
    name: '硬派',
    physical: { agility: -1, dexterity: 0, intelligence: 0, mind: 0, strength: 1, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.5, cautious: 0.0, cheerful: 0.0, trickish: -0.5 },
  },
  {
    id: 44,
    group: 22,
    name: '軟派',
    physical: { agility: 0, dexterity: 1, intelligence: 0, mind: -1, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: -0.5, cautious: 0.0, cheerful: 0.5, trickish: 0.0 },
  },
  {
    id: 45,
    group: 23,
    name: 'お人好し',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: 0.5, trickish: -0.5 },
  },
  {
    id: 46,
    group: 23,
    name: 'ひねくれ者',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.0, cautious: 0.0, cheerful: -0.5, trickish: 0.0 },
  },
  {
    id: 47,
    group: 24,
    name: '名誉こそ命',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: 0.0, brave: 0.5, cautious: -0.5, cheerful: 0.0, trickish: -0.5 },
  },
  {
    id: 48,
    group: 24,
    name: '愛に生きる',
    physical: { agility: 0, dexterity: 0, intelligence: 0, mind: 0, strength: 0, vitality: 0 },
    mental: { aggressive: -0.5, brave: 0.0, cautious: 0.0, cheerful: 0.0, trickish: 0.0 },
  },
];
